# netty port
server:
  port: 9000

# R socket server port & protocol
spring:
  rsocket:
    server:
      port: 7000
      transport: tcp

logging:
  level:
    com:
      example:
        rsocketserver: DEBUG
    org:
      springframework:
        data: DEBUG
    reactor: DEBUG
    io:
      rsocket: DEBUG